"""add account number to accounts

Revision ID: 33e51967017d
Revises: 
Create Date: 2026-03-14 19:30:57.187303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e51967017d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_account_number', 'accounts', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_number', 'accounts', type_='unique')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
